### ISSUE TITLE
update on openvsx

### ISSUE THREAD

**Issue by endigma** [radiolevity/search-lights#11]
https://open-vsx.org/extension/radiolevity/search-lights is on v1.10.1, latest is a few more than that.

**Comment by finnjames** [comment]
It appears that something has happened and I no longer have an access token for the radiolevity namespace on Open VSX. I will report back when I can figure out why.

Edit: looks like it's because I changed my github username 🙄 I am trying to resolve this. Worst case scenario is I'll upload another extension to open VSX with the latest changes, but obviously I'd like to avoid that

**Comment by finnjames** [comment]
Okay, well, that was a hassle. I now have access to the **radiolevity** namespace again and Search Lights is up to date on Open VSX!
